### ISSUE TITLE
Syslog_forwarder pre-start script conflicting with with other pre-start scripts

### ISSUE THREAD

**Issue by jcwinchell** [cloudfoundry/syslog-release#10]
When installing the syslog-release-9 add-on on RabbitMQ and intermittently on MySQL, there are other pre-start scripts running in parallel that attempt to restart rsyslog at the same time causing the deployment to fail. 

The jobs/syslog_forwarder/templates/pre-start.erb script is small so I'm including it here:
#!/bin/bash
set -ex
LOGDIR=/var/vcap/sys/log/syslog_forwarder
mkdir -p ${LOGDIR}
chown -R root:root ${LOGDIR}
chmod 0755 ${LOGDIR}
mkdir -p /var/vcap/data/syslog_forwarder/buffered
chown -R syslog:adm /var/vcap/data/syslog_forwarder/buffered
mkdir -p /etc/rsyslog.d
cp $(dirname $0)/../config/rsyslog.conf /etc/rsyslog.d/rsyslog.conf
service rsyslog restart

That last line needs some error handling to detect if a restart is already in progress. A 10 second sleep would probably do the trick although something more elegant would be preferred.

**Comment by ahevenor** [comment]
@jcwinchell - I have added [#137280739](https://www.pivotaltracker.com/story/show/137280739) to our backlog. We'll review in our weekly planning meeting tomorrow.

**Comment by wfernandes** [comment]
@jcwinchell When deploying metron along side the `syslog_forwarder` job from this syslog-release, you will need to disable metron's syslog daemon config using the property [syslog_daemon_config.enable](https://github.com/cloudfoundry/loggregator/blob/38f3380f328d533a368c1f71158968c00c484dde/jobs/metron_agent/spec#L26)

This will ensure that the syslog configuration from metron will not execute and hence avoiding the race condition.
