### ISSUE TITLE
Ability to add multiple Syslog outputs

### ISSUE THREAD

**Issue by warroyo** [cloudfoundry/syslog-release#11]
It would be great to have the option to configure multiple primary syslog outputs. This could be done by taking in an array of syslog outputs similar to how the failback (https://github.com/cloudfoundry/syslog-release/blob/master/jobs/syslog_forwarder/spec#L32) servers work.

**Comment by Benjamintf1** [comment]
@warroyo Is this still something important?

**Comment by warroyo** [comment]
@Benjamintf1 I still believe this would be useful, I ended up forking the release internally and adding the functionality.

**Comment by Benjamintf1** [comment]
Interesting; we regard a fork as high-signal. We're really curious about your use case - are you trying to send all logs to a second location? A subset?

Assuming you want all logs, you could do it with the `custom_rule` property, too, which might save you the danger of fork-drift.  It'd look something like this:
```
custom_rule: |
  *.* @@address:port;SyslogForwarderTemplate
```

**Comment by anEXPer** [comment]
We're especially interested in your use-case because this _is_ a feature we've been thinking of adding to address another need we're aware of (forwarding different subsets of logs to different places). If we end up doing that work, we'd prefer to ship a feature that works for you, too.

**Comment by warroyo** [comment]
we definitely have fork drift and it would be great not to have to use the forked version anymore. My use case is pretty simple, we needed to send the logs to two different locations. One was for long term security auditing and one for log aggregation. 

I was not aware of the `custom_rule` if that allows me to send to multiple locations then i could definitely use that.

as far as being able to send subsets of logs to different locations I think that would be useful as well. especially if you had the option of sending all logs to both by default, but then being able to exclude log types as needed.

**Comment by anEXPer** [comment]
We wrote some followup-stories to get the custom rule capabilities documented, at least:
https://www.pivotaltracker.com/story/show/156328632 (document adding a remote for everything)
https://www.pivotaltracker.com/story/show/156328688 (document adding a remote for a subset)

We might reach out for feedback on potential implementations of a more first-class approach to these problems at some point.
