### ISSUE TITLE
Logs written during draining are not forwarded by rsyslogd

### ISSUE THREAD

**Issue by maxmoehl** [cloudfoundry/syslog-release#131]
The [drain script](https://github.com/cloudfoundry/syslog-release/blob/main/jobs/syslog_forwarder/templates/drain.erb) stops the `rsyslogd` unit which results in all logs that are written during draining to be lost. Is there a reason for this? Looking at the [BOSH lifecycle](https://bosh.io/docs/job-lifecycle/#stop) of a deployment it should be stopped during the `stop` step.

There is an argument to be made to stop rsyslogd only in the `post-stop` step to retrieve as many logs as possible but this is against the expected lifecycle and could introduce other issues.

**Comment by maxmoehl** [comment]
PR is merged, now we just need a release.

**Comment by ctlong** [comment]
Release is cut!

**Comment by Benjamintf1** [comment]
https://github.com/cloudfoundry/syslog-release/releases/tag/v12.1.5
