### ISSUE TITLE
Proposal: Provide Fluent Bit as alternative to blackbox

### ISSUE THREAD

**Issue by maxmoehl** [cloudfoundry/syslog-release#138]
Follow-up to #131.

In our Cloud Foundry environments we regularly observe log loss during deployments and log file rotation. The loss during file rotation is especially visible on VMs with a high throughput of logs (in our case that's gorouter with more than 350 entries per second). As pointed out by @KarstenSchnitter in #134 we have switched over some deployments to Fluent Bit to mitigate the issue (to some extent).

Our proposal is to offer Fluent Bit either in this release or a dedicated release to give everyone the choice which forwarder to use. My preference would be to provide it as part of the syslog-release to avoid the overhead of yet another release. We would then provide an ops file in cf-d to switch everything over to Fluent Bit.

Comments and feedback are appreciated! Leave a :+1: to show your support for this proposal.

CC: @a18e

**Comment by maxmoehl** [comment]
The missed logs during log file rotation is a different story. So far we only saw that blackbox does miss logs (I have to look up how severe that issue is) but we haven't verified Fluent Bits claim that it handles all rotations properly. But given that it keeps track of its position in the file it should be much easier to properly detect rotates and act accordingly to forward all logs.

**Comment by ctlong** [comment]
Closing in favor of #71. If that doesn't work out we can always re-open this.

**Comment by plowin** [comment]
Hi @ctlong , are there active workstreams for https://github.com/cloudfoundry/syslog-release/issues/71?

**Comment by ctlong** [comment]
@plowin you're asking if there is anyone actively working on it? No, not that I'm aware of.
