### ISSUE TITLE
pre-start fails at rsyslog restart

### ISSUE THREAD

**Issue by acrmp** [cloudfoundry/syslog-release#15]
We are able to deploy syslog-release successfully with our co-located release. When we then update our co-located release the syslog_forwarder fails in pre-start when it attempts to restart rsyslogd.

```
22:14:48 | Updating instance our-instance: our-instance/ca34fd4c-70be-4136-aacf-255128771e88 (0) (canary) (00:00:22)
            L Error: Action Failed get_task: Task 78da8edb-f459-4bc8-5aac-0a9f6bfa7f05 result: 1 of 2 pre-start scripts failed. Failed Jobs: syslog_forwarder. Successful Jobs: our-colocated-job.
```

pre-start.stdout.log:

`timeout: run: rsyslog: (pid 5481) 371s, got TERM`

pre-start.stderr.log:
```
+ cp /var/vcap/jobs/syslog_forwarder/bin/../config/rsyslog.conf /etc/rsyslog.d/rsyslog.conf
+ service rsyslog restart
```

We've encountered this intermittently in the past, but this is now happening consistently in our local bosh-lite environment.

The co-located jobs do not attempt to do any management of rsyslog, we checked this with`grep -R rsyslog /var/vcap/jobs`.

* bosh-lite: 9000.137.0
* stemcell: bosh-warden-boshlite-ubuntu-trusty-go_agent/3312.18
* syslog release: 9

**Comment by cppforlife** [comment]
@acrmp right... `service rsyslog restart` potentially wouldnt work since bosh-lite doesnt run upstart. we'll probably have to add a shim.

**Comment by axelfauvel** [comment]
Hello,

I'm having the same kind of problems on a BOSH 259.0.0 with stemcell bosh-cloudstack-xen-ubuntu-trusty-go_agent/3363.12 & 3263.17, release syslog 11.
Although i've never manager to have a successful deployment .

deployment failure
```
Error 450001: Action Failed get_task: Task fe1ad763-3cab-4ff3-5f0f-09e3dedc573b result: 1 of 2 pre-start scripts failed. Failed Jobs: syslog_forwarder. Successful Jobs: syslog_storer.
```

syslog_forwarder/pre-start.stderr.log
```
+ LOGDIR=/var/vcap/sys/log/syslog_forwarder
+ mkdir -p /var/vcap/sys/log/syslog_forwarder
+ chown -R root:root /var/vcap/sys/log/syslog_forwarder
+ chmod 0755 /var/vcap/sys/log/syslog_forwarder
+ mkdir -p /var/vcap/data/syslog_forwarder/buffered
+ chown -R syslog:adm /var/vcap/data/syslog_forwarder/buffered
+ mkdir -p /etc/rsyslog.d
++ dirname /var/vcap/jobs/syslog_forwarder/bin/pre-start
+ cp /var/vcap/jobs/syslog_forwarder/bin/../config/rsyslog.conf /etc/rsyslog.d/rsyslog.conf
+ service rsyslog restart
stop: Unknown instance: 
start: Job is already running: rsyslog
```

**Comment by Benjamintf1** [comment]
@axelfauvel Just ran this against our local bosh-lite, worked fine. Is it still broken for you?
