### ISSUE TITLE
"group" vs "name"

### ISSUE THREAD

**Issue by dpb587-pivotal** [cloudfoundry/syslog-release#17]
Agent writes out the instance group name to the [`name`](https://github.com/cloudfoundry/bosh-agent/blob/920dd6fc99a5fb8860c215a27e343732c8d66ba8/agent/action/apply.go#L97) instance file, but this release emits instance group name as the [`group`](https://github.com/cloudfoundry/syslog-release/blob/master/jobs/syslog_forwarder/templates/rsyslog.conf.erb#L62) SD field.

Should syslog-release be using `name` instead of `group` for consistency? Using `name` seems weird to me (I imagine `name` being an individually identifiable token), but I'd favor consistency in this situation.

**Comment by Benjamintf1** [comment]
this would be a breaking change, why would it be valuable?

**Comment by dpb587-pivotal** [comment]
This was a while ago, but I think I was just trying to point out an inconsistency between terminology that was being used to try and get some feedback about it. I guess it's not worth keeping this open anymore.
