### ISSUE TITLE
[Question] Send logs of BOSH jobs that log in files

### ISSUE THREAD

**Issue by ivan-sap** [cloudfoundry/syslog-release#2]
Hi, 

I'm looking into this release, since I want to forward log messages from BOSH jobs to a remote syslog server, as suggested by https://github.com/cloudfoundry/loggregator/issues/134#issuecomment-230833117.

I have BOSH job which produces logs and stores them under `/var/vcap/sys/log/<job_name>`. I want to get those logs forwarded to a remote server. In order to achieve this with the syslog-release I see the following solutions:
- I should refactor my BOSH release(s), so the job's stdout and stderr are tee-ed to `logger` (in order to get all logs sinked to the local syslog server).
- I should add additional rsyslogd config that tails all files under `/var/vcap/sys/log/<job_name>` and sends them to the local syslog server. (then the messages will get forwarded to a remote server, since this is the functionality offered by your release).
- I should implement my components in such a way, that they support logging to a syslog server on their own (like for example Concourse's blackbox job [1])

Am I missing something? Do you plan to add functionality that will enable my use-case out of the box (e.g. tailing all files under `/var/vcap/sys/log/<job_name>` and sending them to the configured remote? Or do you have any other release/job that you could recommend for the above?

Thanks!
Kind regards,
Ivan

[1] https://github.com/concourse/concourse/blob/master/jobs/blackbox/spec#L13-L18

**Comment by cppforlife** [comment]
@ivan-sap 

(...missed this repo in my issues dashboard...)

our plan is to actually provide blackbox functionality from this release so that this addon will forward filesystem logs via rsyslog to remote destination. hopefully we can just extract blackbox out of concourse.

**Comment by ivan-sap** [comment]
Hi @cppforlife and thanks for you response.

Any rough idea when this will happen?

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/132264403

**Comment by cppforlife** [comment]
@ivan-sap oops, didnt catch your message. we'll be starting on this shortly.

**Comment by cppforlife** [comment]
That was included in v9.
