### ISSUE TITLE
Ability to designate separate files as separate severity levels

### ISSUE THREAD

**Issue by menicosia** [cloudfoundry/syslog-release#24]
One of the downsides to the, "put all the logs in the right place and let another component manage sending those logs to syslog" is that you lose the feature that syslog supports separate severity levels.

In the past, we have gotten feedback from commercial customers ([#132253669](https://www.pivotaltracker.com/story/show/132253669)) that logging everything at the same severity level is frustrating - it costs them money to store 100% of logs, it makes it hard to find the important stuff amid a sea of debug logs, etc etc.

In many cases in `cf-mysql-release`, it's pretty common for us to at least have two separate log files, one for stdout and one for stderr. It'd be really nice if we could tell syslog-release that entries from each could be logged at different levels, respectively.

**Comment by Benjamintf1** [comment]
@menicosia With our new filtering capability, we should be able to filter out messages at the rsyslog level either by information in the tags, message, job, ect. This currently allows users to ignore debug logs from processes that include DEBUG in the message(for example) which occurs a lot in the messages we have seen. 

Is there still customer want for the ability to better severity log lines from files? Do you have any ideas of how you'd want to prioritize lines from a file(by heuristics on the message? by some convention in the log line? by strictly separated files by log level?)

**Comment by anEXPer** [comment]
This is good feedback. The team is currently getting de-allocated, but this is something for us to explore next time there are engineering resources on this.
