### ISSUE TITLE
syslog forwarding continues after removal of the syslog_forwarder job

### ISSUE THREAD

**Issue by dsabeti** [cloudfoundry/syslog-release#27]
Because rsyslog is always running on BOSH instance groups, and the syslog_forwarder job doesn't remove its `rsyslog.conf` from `/etc/rsyslog.d/`, a deploy that removes the syslog_forwarder job doesn't actually stop syslog from getting sent to the drain.

You can easily reproduce this by colocating the syslog_forwarder on some instance group, and then deploying again to remove the syslog_forwarder. You'll see that your drain (e.g. papertrail) continues to receive logs.

Could a drain script remove the `rsyslog.conf` and restart the rsyslog process?

**Comment by Benjamintf1** [comment]
@dsabeti is this something customers still want to do? If you redeploy with disabled, it should get removed.

**Comment by dsabeti** [comment]
Hey @Benjamintf1. I'm mostly speaking for myself here -- no users or customers have brought this up with me.

As far as using the `disabled` parameter, I assume you mean [this one](https://github.com/cloudfoundry/syslog-release/blob/develop/jobs/syslog_forwarder/spec#L139). It looks like a potential workaround, but I don't think anybody would think to look for that parameter as a way to stop syslogs from being forwarded to a drain. 

Maybe what I'm saying is that this behavior is surprising because it's so different from most other (all other?) BOSH jobs. Operators expect that removing a job from an instance group should change the behavior. I should also mention that this a potentially expensive surprise, if you're forwarding logs to a service that charges you per log line: I originally stumbled onto this behavior when I filled up my papertrail quota.

I think you have a good implicit point that production operators are unlikely to _remove_ the syslog forwarder from their deployments. Still, there are plenty of development teams that only want to set up syslog temporarily -- for example, to validate that new logs have the desired format or contain the correct information -- that it's worth addressing this behavior for them.

**Comment by Benjamintf1** [comment]
Yeah, it's something we've looked into and thought about. I'm not necessarily opposed to doing this in any sense, and think this actually might be a good idea. I'm just wondering how much need drives this, and how much this need has been customer validate, and if we're ok with the downtime we would get between stopping and starting(given the security implications surrounding the downtime)

**Comment by anEXPer** [comment]
We could clean up after ourselves in the drain, and probably should - I find the "I want to stop forwarding logs because something I'm paying for is full/expensive" use case compelling, and suspect that most users will accomplish this by just removing the ops file in cf-d. (Our commercial users do this by enabling the "disabled" property, but that's categorically the wrong approach for OSS.)

We'll talk about this in IPM. We've got good cleanup logic in our pre-start now, so it would be trivial to spread it around.

**Comment by Benjamintf1** [comment]
Manually made a story at https://www.pivotaltracker.com/story/show/156637315

**Comment by Benjamintf1** [comment]
Story was accepted.
