### ISSUE TITLE
Syslog format is not consistent with rfc5424

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/syslog-release#3]
Since the `syslog_forwarder.conf` in this repo was replicated from Loggregator, we'd like to fix the issue here.

Loggregator is looking to deprecating support for setting up syslog forwarding for component logs from Metron Agent and eventually relying on `syslog-release`.

See details in this issue cloudfoundry/loggregator#134

**Comment by keymon** [comment]
Also, note that currently this release does not work fine with logsearch-for-cloudfoundry, which is unfortunate. 

https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/issues/204

**Comment by keymon** [comment]
I did a PR to allow configure different preconfigured templates. The idea is make it easier to transition between formats.

I also think this should be coordinated with other projects, like loggregator metron_agent and logsearch-for-cloudfoundry.
