### ISSUE TITLE
syslog does not send messages to papertrail on bosh-lite

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/syslog-release#32]
Hello, 
we're having an issue with syslog-release `v11` on `bosh-lite` using the `3468.5` stemcell, our logs never show up on papertrail and we can see errors when we do a `ps` on the instance:

```
root          25  0.0  0.0    192    40 ?        S<s  16:29   0:00 runsvdir -P /etc/service log: un: line 19: success: command not found Could not load host key: /etc/ssh/ssh_host_ecdsa_key? Could not load host key: /etc/ssh/ssh_host_ed25519_key? .....rsyslogd: module 'imuxsock' already in this config, cannot be added  [v8.22.0 try http://www.rsyslog.com/e/2221 ] rsyslogd: Could not open output pipe '/dev/xconsole':: No such file or directory [v8.22.0 try http://www.rsyslog.com/e/2039 ]
root          41  0.0  0.0    172     4 ?        S<s  16:29   0:00 runsv rsyslog
syslog      8831  0.0  0.0 422332  4160 ?        S<l  17:49   0:00 rsyslogd -n
syslog      9389  0.1  0.0 251224  8184 ?        S<l  17:49   0:00 /var/vcap/packages/blackbox/bin/blackbox -config=/var/vcap/jobs/syslog_forwarder/config/blackbox_config.yml
root       10009  0.0  0.0  10484  2228 pts/0    S<+  17:50   0:00 grep --color=auto syslog
```

We have also deployed the same manifest to a GCP BOSH director using the same `3468.5` stemcell and it works. 

Could this be an incompatibility with the `bosh-lite` stemcell?

cc @ndhanushkodi

**Comment by dpb587-pivotal** [comment]
Do the bosh-lite VMs have external internet access? Are there any errors in `/var/log/syslog*`-like files or `/var/log/messages` around the issue?

**Comment by zankich** [comment]
@dpb587-pivotal 

yes this bosh-lite has internet access and the contents of `/var/log/syslog` and `/var/log/messages` look like normal syslog type messages, no errors that we can see.

We also do not see any error files in `/var/log/`
```
$ ls /var/log/
audit  auth.log  btmp  debug  kern.log  lastlog  messages  syslog  sysstat  user.log  wtmp
```

**Comment by dpb587-pivotal** [comment]
Odd. Do the settings on your Papertrail account require manually approving source IPs perhaps? Might be interesting to see if the rsyslog process has a connection open to papertrail.

**Comment by zankich** [comment]
I think the issue we're facing is due to this ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/rsyslog/+bug/459730

Previously we were manually configuring our syslog, and those logs showed up on papertrail, so I don't think its a connection issue.

**Comment by Benjamintf1** [comment]
@zankich Is this problem still occurring? How important is getting a fix on this to you?
