### ISSUE TITLE
switch to vendoring golang-1-linux from bosh-packages/golang-release

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/syslog-release#43]
https://github.com/bosh-packages/golang-release and http://bosh.io/docs/package-vendoring/#vendor has some more info.

**Comment by anEXPer** [comment]
It is our understanding that, currently, the only advantage to this switch (given that we have already solved packaging golang for ourselves) would be that it might be easier to update our dependency in the future, especially in CI.

Is this correct, or are there other benefits?

**Comment by Benjamintf1** [comment]
we did this
