### ISSUE TITLE
syslog-release misses some shutdown log messages when deploying an instance_group

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/syslog-release#46]
Perhaps this happens if blackbox is stopped before other processes are stopped/drained.  Can be problematic if attempting to diagnose or identify drain/shutdown problems for jobs.

Thoughts?

**Comment by chombium** [comment]
We have also experienced  some start up log messages are missing. I guess @youngm assumption about the start/stop order is right. We could take a look at it, but for us this problem happened randomly in the past and we didn't find a way to reproduce it. If someone has an idea how to reliably reproduce the problem we could take a look at it.
