### ISSUE TITLE
The config use_tcp_for_file_forwarding_local_transport can cause rsyslog to deadlock and eat memory

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/syslog-release#49]
We tried enabling `use_tcp_for_file_forwarding_local_transport` in our environments and after doing so discovered that some of our vms started running high on memory.  We investigated and saw rsyslog using Gigs of RAM and rsyslog had stopped forwarding messages to drains.

On these boxes if we simply change tcp to udp in blockbox (https://github.com/cloudfoundry/syslog-release/blob/develop/jobs/syslog_forwarder/templates/blackbox_config.yml.erb#L5) then the problem doesn't come back.

The issue seems to mostly happen on our vms running `cloud_controller_ng` with high load.  Haven't seen this issue on any of our other vms.  Not sure if that is just because they are lower load or CC produces larger events than the others?  CC vms in environments with relatively low load also haven't seen the problem.

We don't see anything interesting in blackbox or rsyslog logs giving us an idea of the problem.  Just thought I'd raise what we're seeing.  Not sure how to investigate this further or if I want to. :)

**Comment by youngm** [comment]
It appears this was an issue with the drain we were draining to.  The drain would error out on some particularly long messages and stop reading from the channel causing future requests to backup and eat memory.

**Comment by youngm** [comment]
Thanks for responding @anEXPer 

So, I closed the issue assuming I knew what the problem was but I was unable to duplicate the issue with my drain in a clean test.  So, I no longer think the problem is the fault of my drain.  I've been trying to decide if I should reopen this issue or just forget about it and use udp.  Now that you've responded I think I'll reopen this.

1. The VM was very high on memory ~99-100%.  We didn't notice any particular issues with CC performance or crashes but we didn't really look for them.  In this case Rsyslog was using ~50% of the memory on a server of ~8GB.  So, like you said I wouldn't think it was simple configured rsyslog queues that were filling up to consume that much memory.
2. The local Rsyslog is draining using TCP to our custom drain server.
3. Blackbox appeared to be using a normal amount or memory.  And restarting blackbox didn't change the memory footprint of rsyslog.

One other bit of information.  While experiencing this issue we ran a  `netstat -auntp` and noticed that the `Send-Q` was extremely high (in the millions) from the `Program name` rsyslog to the `Foreign Address` of our custom drain server.  A restart of rsyslog would immediately alleviate this symptom for a time.

We do run the CC clock and Workers on this vm as well but not in debug mode.  Though this is a very high load server for us.

I might also note that while in this broken state no syslog messages from blackbox and this host actually making it to my syslog drain server.  Though other system syslog messages from /var/log/* still make it to my drain server.  I also found it interesting that whenever we noticed this issue the last message to make it to our drain server is an extra long (~12K) message from a CC worker.

Does any of that help? :)

**Comment by anEXPer** [comment]
From what you're describing, I suspect the problem isn't with using tcp for local file forwarding as such... it's just that if you don't, messages will be truncated such that they're below the length that triggers this issue. If you don't mind the truncation, you can just go back to using UDP.

Yeah, I don't find that terribly satisfactory either.

Unfortunately we don't currently have any engineer-time allocated to this release. If we did - or when I find the time myself - I might like to investigate this by manually sending extra-long messages in the range you're talking about on a server that's got something running that outputs a decent volume of more typical-length logs, see if we can figure out what's going on there.

Is your remote rsyslog? Do you know what its $MaxMessageSize is?

**Comment by youngm** [comment]
No we aren't using rsyslog were using a custom adapter.  UDP works fine for us. I'll leave the issue open in case anyone else sees this issue and can shed more light.  Thanks!

**Comment by anEXPer** [comment]
Does your custom adapter specify a max size for incoming messages, and how does it behave when that size is exceeded?

**Comment by youngm** [comment]
yes, the max size is 65K and an error is thrown and the message discarded in this case.  Looking at the logs we've never seen that error thrown.  I also tested this scenario in a clean environment and couldn't duplicate any sort of similar backup of messages issue.

That doesn't mean the fault still isn't my custom drain.  But I wasn't able to determine that conclusively.  I think if I had the time to investigate this issue further the next thing I'd try is an rsyslog drain instead of our custom one to see if we can duplicate the issue.  That would help narrow the focus.  But I haven't had time to do so.

**Comment by youngm** [comment]
Since the ball is still in my court I'd be happy to close this issue if you want until I can get time to prioritize investigating further.

**Comment by anEXPer** [comment]
I'm mostly asking about its behavior because I'm interested in the impact it has on the incoming connection when it discards a message. Especially since you're not seeing an error message on the receiver side, I'm inclined to think something is happening on the rsyslog side.

You can leave it open, and open issue doesn't bother me - even if neither of us can really get to this in depth right now.

**Comment by youngm** [comment]
Sounds good.  LMK if you have any other ideas or things you want me to check.
