### ISSUE TITLE
Make MaxMessageSize configurable

### ISSUE THREAD

**Issue by kongyew** [cloudfoundry/syslog-release#57]
Currently, [MaxMessageSize](https://github.com/cloudfoundry/syslog-release/blob/develop/jobs/syslog_forwarder/templates/syslog-release.conf.erb#L2) is hardcoded.

Can we make MaxMessageSize configurable so user can decide the default size ?

**Comment by anEXPer** [comment]
This shouldn't be hard to do.

I'm anxious about the issues attendant to processing arbitrarily large messages, though.

I note that the commented rsyslog default we're hardcoding to override is 2k, but current rsyslog defaults to 8k, so we should probably bump to that, too.

**Comment by Benjamintf1** [comment]
@kongyew This should be done, sorry for not notifying you. https://github.com/cloudfoundry/syslog-release/blob/91be2b516fad10b319ff47432a8bb030d41851da/jobs/syslog_forwarder/spec#L184
