### ISSUE TITLE
Restart rsyslogd only if the configuration change

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/syslog-release#6]
I think the script should be more smart and restart rsyslogd only if it is required.

The reason is that there is a risk of dropping messages because:
- If rsyslog is using RELP and the upstream endpoint is temporary down for more than 30s
- Messages sent to local rsyslog meanwhile is restarting.

Most of the times, there is no need to restart rsyslog because the config did not change.

We can add some logic like https://github.com/cloudfoundry/loggregator/pull/163/commits/ffe8a6538d8e54dfb3a34e9b652a2060c48fa16b

Let me know what you think, and I can create a PR if you agree.

**Comment by cppforlife** [comment]
@keymon yup, makes sense. PR would be great.

**Comment by cppforlife** [comment]
@keymon i forget can we not do reload in this case instead of restart or new config isnt picked?

**Comment by keymon** [comment]
Yes, it is possible.

**Comment by anEXPer** [comment]
We're still open to a PR on this, but:
- it's been over a year since last activity
- the link to a loggregator example is dead

We're closing this issue; please feel free to open a replacement if you're still interested.
