### ISSUE TITLE
syslog.blackbox.log_filename property seems to be broken

### ISSUE THREAD

**Issue by ansh-SAP** [cloudfoundry/syslog-release#74]
Hi Folks,

The log_filename property which was introduced in v11.5.0 seems to be broken now, atleast from v11.7.5. We don't see the filename appended to the the tag anymore.
But we noticed a "syslog_filename" tag in the logs shipped. Maybe the log_filename property which used to configure the tag to include the filename had been deprecated in lieu of the new "syslog_filename" tag.

**Comment by Benjamintf1** [comment]
Are you sure you mean v11.7.5? I'm not honestly sure what would cause this to change.

**Comment by friegger** [comment]
Turned out that this was a red herring, the `blackbox.log_filename` property is fine.
