### ISSUE TITLE
Consume current golang-release

### ISSUE THREAD

**Issue by joergdw** [cloudfoundry/syslog-release#75]
The current release is not up-to-date. However the golang-versions prior to 1.18.2 and 1.17.10 have [CWE 284](https://cwe.mitre.org/data/definitions/284.html). Could you publish soon the next syslog-release to fix this, please?

**Comment by Benjamintf1** [comment]
@joergdw https://github.com/cloudfoundry/syslog-release/releases/tag/v11.7.10

Done.

**Comment by Benjamintf1** [comment]
@joergdw btw, feel free to reach out in the cloudfoundry slack in #logging-and-metrics about these sorts of things.
