### ISSUE TITLE
syslog_forwarder parameters for mTLS certificates/keys

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/syslog-release#76]
Hi syslog-release Developers,

we want to enable mTLS for our syslog_forwarder configuration. This requires some additional certificate and key files in `/etc/rsyslog.d/`:
```
/etc/rsyslog.d/server-ca.crt
/etc/rsyslog.d/client.crt
/etc/rsyslog.d/client.key
```
We could add the certificates and key as additional parameters in the "spec" file and use the [pre-start.erb](https://github.com/cloudfoundry/syslog-release/blob/main/jobs/syslog_forwarder/templates/pre-start.erb) script to copy the content into the files listed above.

Would this be an acceptable feature for you? If yes, we can try to create a PR.

Thanks and Best Regards,

  Jochen.

**Comment by jochenehret** [comment]
We will try to create a PR for this issue!

**Comment by jochenehret** [comment]
First draft: https://github.com/cloudfoundry/syslog-release/pull/77

**Comment by stephanme** [comment]
#78 proposes a simpler solution to add mTLS certs compared to #77 (which got basically rejected).

**Comment by Benjamintf1** [comment]
Should be out in https://github.com/cloudfoundry/syslog-release/releases/tag/v11.8.0. 

Feel free to open a new pr/issue if you want to pursue multiple forwarding configs.
