### ISSUE TITLE
Operators may think that TLS encryption is enabled when it's actually not

### ISSUE THREAD

**Issue by mfine30** [cloudfoundry/syslog-release#8]
Setting `syslog.tls_enabled: true` as well as `syslog.ca_cert: | ...` is required to actually enable encrypted syslogging. While accepting a story, I set the ca_cert but forgot to say `tls_enabled: true`. This lead me to be very confused why my logs weren't encrypted. 

It would be nice if the template raised when a cert is provided and tls_enabled is set to `false`.

**Comment by cppforlife** [comment]
fine suggestion!

**Comment by cppforlife** [comment]
Pulled in.
