### ISSUE TITLE
Syslog forwarding release can not be disabled

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/syslog-release#9]
There is not a first class mechanism (on/off property) to disable syslog forwarding.

We would need this for people to migrate from metron configuring rsyslog.

**Comment by cppforlife** [comment]
It's implemented at the BOSH level: when opting in specify addon inclusion rules: http://bosh.io/docs/runtime-config#addons

**Comment by anEXPer** [comment]
Worth noting, we've actually added this option in an effort to deprecate syslog-migration-release. We hope to get rid of it as soon as certain commercial distributors support addon management.
