### ISSUE TITLE
Remove `relp` protocol

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/syslog-release#99]
From https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/249#issuecomment-1301043991:
> While we have not made changes to remove relp, it has gotten a lot less support as a usecase compared to tcp/tls. We don't even have a [test for relp at the moment](https://github.com/cloudfoundry/syslog-release/tree/main/tests/manifests). Broader industry support for relp is pretty low, and it doesn't seem to bring much to the table as a protocol. We should probably consider removing relp as a protocol from syslog-release.

We don't currently test this release with the `relp` protocol, and very likely it's completely broken because none of the configuration options we currently set appear to match options in the [omrelp manual](https://www.rsyslog.com/doc/v8-stable/configuration/modules/omrelp.html).

**Comment by h0nIg** [comment]
@ctlong IMHO it is not required to have a 1:1 mapping for additional parameters, it is sufficient to offer the most important ones and everything else can be setup via custom rule? https://github.com/cloudfoundry/syslog-release/blob/main/jobs/syslog_forwarder/spec#L71

**Comment by ctlong** [comment]
Given only @h0nIg engaged here, and in favor of keeping the relp protocol, I'm going to close this issue as not planned.
